# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-28 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200228_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runner',
            old_name='nombres',
            new_name='name',
        ),
    ]
