# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-28 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200228_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runner',
            old_name='apellidos',
            new_name='last_names',
        ),
        migrations.RenameField(
            model_name='runner',
            old_name='name',
            new_name='names',
        ),
    ]
