# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200228_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
