# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-28 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_runner_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='document_type',
            field=models.CharField(choices=[('CEDULA', 'CC'), ('TARJETA', 'TI')], default='CC', max_length=128),
        ),
    ]
