# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-29 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_runner_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='document_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runner',
            name='document_type',
            field=models.CharField(choices=[('C.C.', 'CÉDULA DE CIUDADANÍA'), ('C.E.', 'CÉDULA DE EXTRANJERIA'), ('C.I.P.', 'CÉDULA DE IDENTIDAD POLICIAL'), ('C.M.', 'CÉDULA MILITAR'), ('C.E.I.L.', 'CÓD. ESTUDIANTE I.LENGUAS'), ('C.EST.', 'CÓDIGO ESTUDIANTE'), ('C.REG.', 'CONTRASEÑA REGISTRADURIA'), ('E.EXT.', 'ENTIDADES EXTRANJERAS'), ('L.M.', 'LIBRETA MILITAR'), ('NIT', 'NIT'), ('OTHERS', 'OTROS DOCUMENTOS'), ('PASSPORT', 'PASAPORTE'), ('C.PASSPORT', 'PASAPORTE COLOMBIANO'), ('R.C.', 'REGISTRO CIVIL'), ('R.C.', 'SIN DOCUMENTO'), ('T.I.', 'TARJETA DE IDENTIDAD'), ('TAX ID', 'TAX ID/NÚMERO DE IMPUESTO PARA'), ('VAT', 'VAT/NÚMERO DE IMPUESTO PARA PR')], default='CC', max_length=128),
        ),
    ]
