# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-02 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200302_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='runner',
            name='cellphone',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='document_number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='runner',
            name='email',
            field=models.EmailField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='emergency_contact',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='runner',
            name='emergency_contact_cellphone',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='runner',
            name='first_lastname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='runner',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='runner',
            name='health',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='runner',
            name='second_lastname',
            field=models.CharField(max_length=128),
        ),
    ]
